#!/bin/bash

mkdir -p test-env
cd test-env
cargo build --features="bin_deps" && \
cargo test --features="test_local_io" && \
cargo test --features="initial_input_data"
ret=$?
cd ..
rm -r test-env
exit $ret
